[tool.poetry]
name = "django-swagger-tester"
version = "2.1.3"  # Remember to also change in django_swagger_tester/__init__.py version
description = "Django test utility for validating Swagger documentation"
authors = ["Sondre Lillebø Gundersen <sondrelg@live.no>"]
license = "BSD-4-Clause"
readme = "docs/PYPI_README.rst"
homepage = "https://github.com/snok/django-swagger-tester"
repository = "https://github.com/snok/django-swagger-tester"
documentation = "https://django-swagger-tester.readthedocs.io/en/latest/"
keywords = ['openapi', 'swagger', 'api', 'testing', 'django']
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Web Environment',
    'Framework :: Pytest',
    'Framework :: Django',
    'Framework :: Django :: 2.2',
    'Framework :: Django :: 3.0',
    'Framework :: Django :: 3.1',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Application Frameworks',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Documentation',
    'Topic :: Software Development :: Testing',
    'Topic :: Software Development :: Testing :: Unit',
]
include = ["CHANGELOG.rst"]

[tool.poetry.dependencies]
python = "^3.6"
djangorestframework = "*"
django = "^2.2 || ^3.0"

[tool.poetry.dev-dependencies]
pre-commit = "2.1.1"
drf-yasg = "^1.17.1"
pyYAML = "5.3.1"
djangorestframework_camel_case = "1.2.0"
pytest = "^6.2"
pytest-cov = "2.10.1"
pytest-django = "4.1.0"
flake8 = "*"
sphinx = "^3.3.1"
sphinx_rtd_theme = "^0.5.0"
drf-spectacular = "^0.11.1"
ipython = "^7.16.1"
black = "^20.8b1"
isort = "^5.6.4"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
    (\.eggs|\.git|\.hg|\.mypy_cache|\.tox|\.venv|\venv|\.github|\docs|\tests|\__pycache__)
)
'''

[tool.isort]
profile = "black"
src_paths = ["django_swagger_tester"]
combine_as_imports = true
line_length = 120
sections = [
    'FUTURE',
    'STDLIB',
    'DJANGO',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER'
]
known_django = ['django']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
